# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-23 06:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotation', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quotation',
            name='qotat_no',
        ),
        migrations.AddField(
            model_name='item',
            name='slug',
            field=models.SlugField(default=1, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='quotation',
            name='qotat',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
