# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-23 07:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotation', '0002_auto_20160423_0630'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotation',
            name='qotat',
            field=models.IntegerField(),
        ),
    ]
