# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-23 08:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotation', '0003_auto_20160423_0725'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='quotation',
            new_name='qotat_no',
        ),
        migrations.RemoveField(
            model_name='quotation',
            name='qotat',
        ),
        migrations.AddField(
            model_name='quotation',
            name='qotat_no',
            field=models.IntegerField(default=1, unique=True),
            preserve_default=False,
        ),
    ]
