# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-23 11:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotation', '0004_auto_20160423_0854'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='name',
            new_name='name1',
        ),
        migrations.AddField(
            model_name='item',
            name='name2',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
